# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyMainWindow(object):
    def setupUi(self, MyMainWindow):
        MyMainWindow.setObjectName("MyMainWindow")
        MyMainWindow.resize(1106, 830)
        self.centralwidget = QtWidgets.QWidget(MyMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.frameMeasure = QtWidgets.QFrame(self.centralwidget)
        self.frameMeasure.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMeasure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMeasure.setObjectName("frameMeasure")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameMeasure)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3.addWidget(self.frameMeasure, 1, 0, 1, 1)
        MyMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MyMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyMainWindow)
        self.statusbar.setObjectName("statusbar")
        MyMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MyMainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MyMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionMeasureConfig = QtWidgets.QAction(MyMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMeasureConfig.setIcon(icon)
        self.actionMeasureConfig.setObjectName("actionMeasureConfig")
        self.actionStartMeasure = QtWidgets.QAction(MyMainWindow)
        self.actionStartMeasure.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/images/测量.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartMeasure.setIcon(icon1)
        self.actionStartMeasure.setObjectName("actionStartMeasure")
        self.actionUDPConfig = QtWidgets.QAction(MyMainWindow)
        self.actionUDPConfig.setCheckable(True)
        self.actionUDPConfig.setIcon(icon)
        self.actionUDPConfig.setObjectName("actionUDPConfig")
        self.menu.addAction(self.actionUDPConfig)
        self.menu.addAction(self.actionMeasureConfig)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionUDPConfig)
        self.toolBar.addAction(self.actionMeasureConfig)
        self.toolBar.addAction(self.actionStartMeasure)

        self.retranslateUi(MyMainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MyMainWindow)

    def retranslateUi(self, MyMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MyMainWindow.setWindowTitle(_translate("MyMainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MyMainWindow", "通道1~6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MyMainWindow", "通道7~12"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MyMainWindow", "通道13~18"))
        self.menu.setTitle(_translate("MyMainWindow", "设置"))
        self.toolBar.setWindowTitle(_translate("MyMainWindow", "toolBar"))
        self.actionMeasureConfig.setText(_translate("MyMainWindow", "测量设置"))
        self.actionStartMeasure.setText(_translate("MyMainWindow", "开始测量"))
        self.actionUDPConfig.setText(_translate("MyMainWindow", "UDP通信设置"))
        self.actionUDPConfig.setToolTip(_translate("MyMainWindow", "UDP通信设置"))
import image_rc
