# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWidget(object):
    def setupUi(self, ConfigWidget):
        ConfigWidget.setObjectName("ConfigWidget")
        ConfigWidget.resize(152, 239)
        ConfigWidget.setStyleSheet("image: url(:/png/images/加号.png);")

        self.retranslateUi(ConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(ConfigWidget)

    def retranslateUi(self, ConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        ConfigWidget.setWindowTitle(_translate("ConfigWidget", "Form"))
import image_rc
