# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MeasureWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeasureWidget(object):
    def setupUi(self, MeasureWidget):
        MeasureWidget.setObjectName("MeasureWidget")
        MeasureWidget.resize(183, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(MeasureWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelChannel = QtWidgets.QLabel(MeasureWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelChannel.sizePolicy().hasHeightForWidth())
        self.labelChannel.setSizePolicy(sizePolicy)
        self.labelChannel.setObjectName("labelChannel")
        self.verticalLayout.addWidget(self.labelChannel)
        self.labelX1 = QtWidgets.QLabel(MeasureWidget)
        self.labelX1.setObjectName("labelX1")
        self.verticalLayout.addWidget(self.labelX1)
        self.labelX2 = QtWidgets.QLabel(MeasureWidget)
        self.labelX2.setObjectName("labelX2")
        self.verticalLayout.addWidget(self.labelX2)
        self.labelDeltaX = QtWidgets.QLabel(MeasureWidget)
        self.labelDeltaX.setObjectName("labelDeltaX")
        self.verticalLayout.addWidget(self.labelDeltaX)
        self.labelY1 = QtWidgets.QLabel(MeasureWidget)
        self.labelY1.setObjectName("labelY1")
        self.verticalLayout.addWidget(self.labelY1)
        self.labelY2 = QtWidgets.QLabel(MeasureWidget)
        self.labelY2.setObjectName("labelY2")
        self.verticalLayout.addWidget(self.labelY2)
        self.labelDeltaY = QtWidgets.QLabel(MeasureWidget)
        self.labelDeltaY.setObjectName("labelDeltaY")
        self.verticalLayout.addWidget(self.labelDeltaY)

        self.retranslateUi(MeasureWidget)
        QtCore.QMetaObject.connectSlotsByName(MeasureWidget)

    def retranslateUi(self, MeasureWidget):
        _translate = QtCore.QCoreApplication.translate
        MeasureWidget.setWindowTitle(_translate("MeasureWidget", "Form"))
        self.labelChannel.setText(_translate("MeasureWidget", "通道标识"))
        self.labelX1.setText(_translate("MeasureWidget", "X1"))
        self.labelX2.setText(_translate("MeasureWidget", "X2"))
        self.labelDeltaX.setText(_translate("MeasureWidget", "ΔX"))
        self.labelY1.setText(_translate("MeasureWidget", "Y1"))
        self.labelY2.setText(_translate("MeasureWidget", "Y2"))
        self.labelDeltaY.setText(_translate("MeasureWidget", "ΔY"))
