# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MeasureWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeasureWidget(object):
    def setupUi(self, MeasureWidget):
        MeasureWidget.setObjectName("MeasureWidget")
        MeasureWidget.resize(165, 156)
        self.verticalLayout = QtWidgets.QVBoxLayout(MeasureWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(MeasureWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: black;\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"    background-color: rgb(170, 170, 255);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelX1 = QtWidgets.QLabel(self.groupBox)
        self.labelX1.setObjectName("labelX1")
        self.verticalLayout_2.addWidget(self.labelX1)
        self.labelX2 = QtWidgets.QLabel(self.groupBox)
        self.labelX2.setObjectName("labelX2")
        self.verticalLayout_2.addWidget(self.labelX2)
        self.labelDeltaX = QtWidgets.QLabel(self.groupBox)
        self.labelDeltaX.setObjectName("labelDeltaX")
        self.verticalLayout_2.addWidget(self.labelDeltaX)
        self.labelY1 = QtWidgets.QLabel(self.groupBox)
        self.labelY1.setObjectName("labelY1")
        self.verticalLayout_2.addWidget(self.labelY1)
        self.labelY2 = QtWidgets.QLabel(self.groupBox)
        self.labelY2.setObjectName("labelY2")
        self.verticalLayout_2.addWidget(self.labelY2)
        self.labelDeltaY = QtWidgets.QLabel(self.groupBox)
        self.labelDeltaY.setObjectName("labelDeltaY")
        self.verticalLayout_2.addWidget(self.labelDeltaY)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(MeasureWidget)
        QtCore.QMetaObject.connectSlotsByName(MeasureWidget)

    def retranslateUi(self, MeasureWidget):
        _translate = QtCore.QCoreApplication.translate
        MeasureWidget.setWindowTitle(_translate("MeasureWidget", "Form"))
        self.groupBox.setTitle(_translate("MeasureWidget", "通道标识"))
        self.labelX1.setText(_translate("MeasureWidget", "X1"))
        self.labelX2.setText(_translate("MeasureWidget", "X2"))
        self.labelDeltaX.setText(_translate("MeasureWidget", "ΔX"))
        self.labelY1.setText(_translate("MeasureWidget", "Y1"))
        self.labelY2.setText(_translate("MeasureWidget", "Y2"))
        self.labelDeltaY.setText(_translate("MeasureWidget", "ΔY"))
