# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UdpConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UdpConfig(object):
    def setupUi(self, UdpConfig):
        UdpConfig.setObjectName("UdpConfig")
        UdpConfig.resize(280, 445)
        self.gridLayout_3 = QtWidgets.QGridLayout(UdpConfig)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(30, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditClientPort1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditClientPort1.setObjectName("lineEditClientPort1")
        self.gridLayout_2.addWidget(self.lineEditClientPort1, 1, 1, 1, 1)
        self.lineEditClientIP1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditClientIP1.setObjectName("lineEditClientIP1")
        self.gridLayout_2.addWidget(self.lineEditClientIP1, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(30, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditServerIP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditServerIP.setObjectName("lineEditServerIP")
        self.gridLayout.addWidget(self.lineEditServerIP, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditServerPort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditServerPort.setObjectName("lineEditServerPort")
        self.gridLayout.addWidget(self.lineEditServerPort, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(UdpConfig)
        self.btnOpen.setMinimumSize(QtCore.QSize(100, 50))
        self.btnOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpen.setIcon(icon)
        self.btnOpen.setIconSize(QtCore.QSize(40, 40))
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout_3.addWidget(self.btnOpen, 4, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(30, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEditClientPort2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditClientPort2.setObjectName("lineEditClientPort2")
        self.gridLayout_4.addWidget(self.lineEditClientPort2, 1, 1, 1, 1)
        self.lineEditClientIP2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditClientIP2.setObjectName("lineEditClientIP2")
        self.gridLayout_4.addWidget(self.lineEditClientIP2, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(30, -1, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEditClientPort3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditClientPort3.setObjectName("lineEditClientPort3")
        self.gridLayout_6.addWidget(self.lineEditClientPort3, 1, 1, 1, 1)
        self.lineEditClientIP3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditClientIP3.setObjectName("lineEditClientIP3")
        self.gridLayout_6.addWidget(self.lineEditClientIP3, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 3, 0, 1, 3)

        self.retranslateUi(UdpConfig)
        QtCore.QMetaObject.connectSlotsByName(UdpConfig)

    def retranslateUi(self, UdpConfig):
        _translate = QtCore.QCoreApplication.translate
        UdpConfig.setWindowTitle(_translate("UdpConfig", "Form"))
        self.groupBox_2.setTitle(_translate("UdpConfig", "下位机1设置（CH1 - CH8）"))
        self.label_3.setText(_translate("UdpConfig", "IP"))
        self.label_4.setText(_translate("UdpConfig", "端口"))
        self.groupBox.setTitle(_translate("UdpConfig", "上位机设置"))
        self.label.setText(_translate("UdpConfig", "IP"))
        self.label_2.setText(_translate("UdpConfig", "端口"))
        self.groupBox_3.setTitle(_translate("UdpConfig", "下位机2设置（CH9 - CH16）"))
        self.label_6.setText(_translate("UdpConfig", "IP"))
        self.label_7.setText(_translate("UdpConfig", "端口"))
        self.groupBox_4.setTitle(_translate("UdpConfig", "下位机3设置（CH17 - CH18）"))
        self.label_8.setText(_translate("UdpConfig", "IP"))
        self.label_10.setText(_translate("UdpConfig", "端口"))
import image_rc
