# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UdpConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UdpConfig(object):
    def setupUi(self, UdpConfig):
        UdpConfig.setObjectName("UdpConfig")
        UdpConfig.resize(398, 282)
        self.gridLayout_3 = QtWidgets.QGridLayout(UdpConfig)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(30, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditServerIP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditServerIP.setObjectName("lineEditServerIP")
        self.gridLayout.addWidget(self.lineEditServerIP, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditServerPort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditServerPort.setObjectName("lineEditServerPort")
        self.gridLayout.addWidget(self.lineEditServerPort, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 3)
        self.btnOpen = QtWidgets.QPushButton(UdpConfig)
        self.btnOpen.setMinimumSize(QtCore.QSize(100, 50))
        self.btnOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpen.setIcon(icon)
        self.btnOpen.setIconSize(QtCore.QSize(40, 40))
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout_3.addWidget(self.btnOpen, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(UdpConfig)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    color: rgb(85, 170, 255);\n"
"    font-family: \'微软雅黑\';\n"
"    font-weight: bold;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(30, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditClient1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditClient1.setObjectName("lineEditClient1")
        self.gridLayout_2.addWidget(self.lineEditClient1, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditClient2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditClient2.setObjectName("lineEditClient2")
        self.gridLayout_2.addWidget(self.lineEditClient2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEditClient3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditClient3.setObjectName("lineEditClient3")
        self.gridLayout_2.addWidget(self.lineEditClient3, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 1, 1, 1)

        self.retranslateUi(UdpConfig)
        QtCore.QMetaObject.connectSlotsByName(UdpConfig)

    def retranslateUi(self, UdpConfig):
        _translate = QtCore.QCoreApplication.translate
        UdpConfig.setWindowTitle(_translate("UdpConfig", "Form"))
        self.groupBox.setTitle(_translate("UdpConfig", "上位机设置"))
        self.label.setText(_translate("UdpConfig", "上位机IP"))
        self.label_2.setText(_translate("UdpConfig", "上位机端口"))
        self.groupBox_2.setTitle(_translate("UdpConfig", "下位机设置"))
        self.label_3.setText(_translate("UdpConfig", "下位机1 IP（CH1 - CH8）"))
        self.label_4.setText(_translate("UdpConfig", "下位机2 IP（CH9 - CH16）"))
        self.label_5.setText(_translate("UdpConfig", "下位机3 IP（CH17 - CH18）"))
import image_rc
